baseurl = "https://mediaelch.github.io/mediaelch-blog/" # Hostname (and path) to the root.
title = "Blog | MediaElch" # Site title.
theme = "mediaelch-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "MediaElch"
    description = "Media Manager for Kodi"
    keywords = "blog,developer,personal"
    info = "Media Manager for Kodi"
    avatarurl = "images/mediaelch.png"
    #footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Komet/MediaElch"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/mediaelch/"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "https://mediaelch.github.io/mediaelch-doc/about.html"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "GitHub"
        weight = 3
        url = "https://github.com/Komet/MediaElch"

[markup.goldmark.renderer]
unsafe = true
